### ISSUE TITLE
Swift Concurrency support

### ISSUE THREAD

**Issue by griffin-stewie** [apple/swift-argument-parser#368] opened 2021-10-30 10:45 UTC
Xcode 13.2 Beta is released now. We are getting closer to use Swift Concurrency in the real life. I wish [async branch](https://github.com/apple/swift-argument-parser/tree/async) will be merged.

Thank you.

**Comment by Jerry-Carter** [comment] 2021-11-03 19:38
This seems like a duplicate of [Issue #326](https://github.com/apple/swift-argument-parser/issues/326)

**Comment by natecook1000** [comment] 2021-12-10 22:01
Tracked in #326.

**Closed by natecook1000** 2021-12-10 22:01 UTC
