### ISSUE TITLE
Compilation failure to compile interpolated help screen.

### ISSUE THREAD

**Issue by vlm** [apple/swift-argument-parser#220] opened 2020-08-01 02:23 UTC
The argument parser doesn't allow interpolated string to be used as help arguments in Swift-5.2.4.

**ArgumentParser version:** `0.2.0`, `0.2.1`.
**Swift version:** Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)

### Steps to Reproduce

Create the following option in any parser:

```
    @Option(help: "foo \(1)")
    var foo: Int = 1
```

### Expected behavior

The code compiles.

### Actual behavior

```swift
<unknown>:0: error: cannot assign to immutable expression of type '(String) -> ()'
/Path/to/Source.swift:15:56: error: cannot assign to immutable expression of type '(Int) -> ()'
```

**Comment by natecook1000** [comment] 2020-08-03 18:54
Thanks for the report, @vlm!

I've found two workarounds for this issue:
1. Upgrade to Swift 5.3
2. Define the help explicitly outside of the property declaration

```swift
let fooHelp: ArgumentHelp = "foo \(1)"

struct Example: ParsableArguments {
    @Option(help: fooHelp) 
    var foo = 1
}
```

**Comment by natecook1000** [comment] 2021-04-21 06:49
Closing this, as the problem is fixed in current/future Swift versions. Please feel free to re-open the issue if you'd like to discuss further!

**Closed by natecook1000** 2021-04-21 06:49 UTC
Labels: bug, wontfix
